### ISSUE TITLE
SqueezePlay vs SqueezeOS

### ISSUE THREAD

**Issue by andistorm** [LMS-Community/squeezeplay#7]
What are the differences between SqueezeOS and SqueezePlay which one do I need to build an OS for my Squeezebox Touch?

**Comment by mherger** [comment]
SqueezeOS is the operating systems, SqueezePlay the UI to it. The latter can be run on many platforms other than SqueezeOS.

I see that you've joined the community on forums.slimdevices.com which is the right place to ask this kind of question. I'm going to close this ticket, as it's not an issue. Thanks for your understanding!
