### ISSUE TITLE
Secret(s) found: 18 - [Product Security - Secret Scanning]

### ISSUE THREAD

**Issue by nhamzi** [LMS-Community/squeezeplay#9]
This is automated issue created by Logitech Secret Scanner v1.0 - Nabil Hamzi

It seems that information looking like a secret (password, token, credentials, ...) has been identified in this github repository.
We should avoid as much as possible to store secrets in Github code repository. Github has an 'encrypted secrets' feature for this.
Please react on this thread with @nhamzi for any question.

Here are the findings, SecretLink contains the link to the sensitive value to be renewed, refreshed and deleted.

SecretLink=https://github.com/Logitech/squeezeplay/blob/be6b4d745d787632b750be002d031c82364a7d06/src/squeezeplay_squeezeos/share/applets/ImageViewer/ImageSourceFlickr.lua#L45-L45
SecretLink=https://github.com/Logitech/squeezeplay/blob/e7ac2c2f9225fbe9d0a8ec9fd7062b8de4dd7b79/src/pkg/jive/share/applets/Flickr/FlickrApplet.lua#L70-L70
SecretLink=https://github.com/Logitech/squeezeplay/blob/54e65f49372c614ff9aa86f385979bc91bb6889c/src/glib-2.16.4/docs/reference/glib/html/ix01.html#L3396-L3396
SecretLink=https://github.com/Logitech/squeezeplay/blob/5d3ceddf12602b8d6acfca450e7064a7639c2cd8/src/glib-2.16.4/glib/gunicollate.c#L397-L397
SecretLink=https://github.com/Logitech/squeezeplay/blob/5d3ceddf12602b8d6acfca450e7064a7639c2cd8/src/glib-2.16.4/glib/gunicollate.c#L420-L420
SecretLink=https://github.com/Logitech/squeezeplay/blob/5d3ceddf12602b8d6acfca450e7064a7639c2cd8/src/glib-2.16.4/glib/gunicollate.c#L488-L488
SecretLink=https://github.com/Logitech/squeezeplay/blob/5d3ceddf12602b8d6acfca450e7064a7639c2cd8/src/glib-2.16.4/tests/unicode-collate.c#L105-L105
SecretLink=https://github.com/Logitech/squeezeplay/blob/f3a4ac8ef1bfe6dd67572a00ee677d4c1a18ce54/src/SDL-1.2.13/src/video/windx5/SDL_dx5video.c#L620-L620
SecretLink=https://github.com/Logitech/squeezeplay/blob/e6d71d51b9220ad25ee1ddd5e35b1905921312b3/src/pkg/SDL-1.2.11/src/video/windx5/SDL_dx5video.c#L619-L619
SecretLink=https://github.com/Logitech/squeezeplay/blob/d53cb356d259d810111651461202ff3dd3526b6e/src/src/pkg/SDL-1.2.11/src/video/windx5/SDL_dx5video.c#L619-L619
SecretLink=https://github.com/Logitech/squeezeplay/blob/72f833ec0c0f92507a65a583e308a0484233cbc3/src/pkg/SDL-1.2.11/src/video/windx5/SDL_dx5video.c#L619-L619
SecretLink=https://github.com/Logitech/squeezeplay/blob/f3a4ac8ef1bfe6dd67572a00ee677d4c1a18ce54/src/SDL-1.2.13/src/video/x11/SDL_x11video.c#L171-L171
SecretLink=https://github.com/Logitech/squeezeplay/blob/e6d71d51b9220ad25ee1ddd5e35b1905921312b3/src/pkg/SDL-1.2.11/src/video/x11/SDL_x11video.c#L165-L165
SecretLink=https://github.com/Logitech/squeezeplay/blob/d53cb356d259d810111651461202ff3dd3526b6e/src/src/pkg/SDL-1.2.11/src/video/x11/SDL_x11video.c#L165-L165
SecretLink=https://github.com/Logitech/squeezeplay/blob/72f833ec0c0f92507a65a583e308a0484233cbc3/src/pkg/SDL-1.2.11/src/video/x11/SDL_x11video.c#L165-L165
SecretLink=https://github.com/Logitech/squeezeplay/blob/e6d71d51b9220ad25ee1ddd5e35b1905921312b3/src/pkg/jive/share/applets/Flickr/FlickrApplet.lua#L62-L62
SecretLink=https://github.com/Logitech/squeezeplay/blob/d53cb356d259d810111651461202ff3dd3526b6e/src/src/pkg/jive/share/applets/Flickr/FlickrApplet.lua#L62-L62
SecretLink=https://github.com/Logitech/squeezeplay/blob/1bd15a861abf76663a0033afee9d7ee300711e68/src/pkg/jive/share/applets/Flickr/FlickrApplet.lua#L59-L59

**Comment by etissotdupont** [comment]
@mherger can you please take care of this one?

**Comment by mherger** [comment]
Sent a mail to Flickr asking about these keys. But I don't have any info other than those keys. Not sure they will be able to help...

**Comment by nhamzi** [comment]
I have to provide an user and an account :/
![image](https://user-images.githubusercontent.com/73521931/208399721-9d02beec-66f9-47ce-8e77-f3a2acf8c3c9.png)

**Comment by mherger** [comment]
I put "unknown" in there.

**Comment by nhamzi** [comment]
@mherger I think as these secrets are no more present in the master branch nor latest version.
I suggest we delete these secret from the git history => https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

What do you think?

**Comment by mherger** [comment]
This is a public repository - we can't remove secrets from clones. Therefore this effort would be a waste of time.

**Comment by nhamzi** [comment]
RIght, let me close this issue.
